### ISSUE TITLE
Chief of Monitors

### ISSUE THREAD

**Issue by majamassarini** [packit/weekly-roles#325]
As **chief of monitors** watch [Sentry](https://sentry.io/organizations/red-hat-it/issues/?project=1767823) for issues:

 * On the Monday check all the alerts for the past week-end
 * Fix recurring alerts
   * Deploy fixes to production for issues that cause major disruption or complete downtime
   * Verify no alerts are being triggered any more
 * More complicated issues should be brought to the team and prioritized correctly.
 * Clean all the past alerts so we have easy to navigate dashboard
 * Link github and sentry issues

React to alerts arriving through email and check the [SLO monitoring page](http://metrics.osci.redhat.com/d/VXwH27XMk/rhel-infrastructure-and-service-health?orgId=1) (Packit section) and respond to the email so others know what is happening. Suggest updates of the alert thresholds if needed.

Watch our other two Grafana dashboards as well:
* [Celery Monitoring](http://metrics.osci.redhat.com/d/3OBI1flGz/celery-monitoring-with-flower?orgId=1&from=now-24h&to=now&refresh=10s)
* [Packit Monitoring](http://metrics.osci.redhat.com/d/iuAkAaWMk/packit?orgId=1)

As **CI Hacker** you are responsible throughout the sprint for keeping the CI green, that is to look for and drive the resolution of systematic CI failures.

It can happen that a CI system has an outage. For problems related to Zuul, please reach out to the team at `#sf-ops` matrix.org channel.

Once pre-commit-ci user creates updates to our pre-commit configs, [take care of the pull requests](https://github.com/search?q=org%3Apackit+pre-commit+autoupdate&type=pullrequests&ref=advsearch&state=open):

**Comment by mfocko** [comment]
Taking over, so we can rotate, cause no one assigned broke the GH Action
